export enum ROUTES {
    //Routes Page
    DEFAULT = "/en",
    DASH_BOARD = "/dashboard",
    ACCOUNTS = "/accounts",
    CUSTOMER = "/accounts/customer",
    CUSTOMER_DETAILS = "/accounts/customer/[id]",
    BRANCH = "/accounts/branch",
    BRANCH_DETAILS = "/accounts/branch/[id]",
    SERVICES = "/services",
    SERVICE_FEE = "/service-fee",
    TRANSACTION_FEE = "/transaction-fee",
    PROMOTIONS = "/promotions",
    TICKETS = "/tickets",
    COMBO_SERVICE = "/combo-service",
    POSTS = "/posts",
    POST_DETAILS = "/posts/[postId]",
    SPECIES = "/species",
    BREEDS = "/breeds",
    VACCINES = "/vaccines",
    PETS = "/pets",
    PET_DETAILS = "/pets/[id]",
    SALE_TRANSACTION = "/sale-transaction",
    SALE_TRANSACTION_DETAILS = "/sale-transaction/[id]",
    BREEDING_TRANSACTION = "/breeding-transaction",
    BREEDING_TRANSACTION_DETAILS = "/breeding-transaction/[breedingTransactionId]",
    ORDERS = "/orders",
    CREATE_ORDER = "/orders/create-order",
    ANOTHER_SERVICE = "/another-service",
    LOGIN = "/auth/login",
    FORGOT_PASSWORD = "/auth/forgot-password",
    CONFIGURATION_MANAGEMENT = "/configurations",
}
